// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using crypto_bot_api.Data;

#nullable disable

namespace crypto_bot_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250504063915_TradeRecords")]
    partial class TradeRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("crypto_bot_api.Data.TradeRecords", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TradeId"));

                    b.Property<decimal?>("AcquiredPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AcquiredQuantity")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OffloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PercentageOfReturn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SoldPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("TradeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TradeType")
                        .HasColumnType("text");

                    b.HasKey("TradeId");

                    b.ToTable("TradeRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
